title: TX_RX_esp32CAM_MKRWAN
description: Long-range image transmission via LoRa (ESP32-CAM + MKR WAN, 434 MHz)

# Important so links & assets work under your repo path
baseurl: "/TX_RX_esp32CAM_MKRWAN"

# Site language
lang: en

# Author info
author: "Fatimazahra El Meady & Anass El Kabbaj"

# Disable theme, since you’re using your own _layouts/default.html
theme: null
